version: '3.8'

services:
  ai-creator-backend:
    build: ./backend/
    ports:
      - "8080:8080"

    networks:
      - ai-creator-network

  frontend:
    build: ./simple-frontend/
    ports:
      - "3000:3000"
    networks:
        - ai-creator-network    

networks:
  ai-creator-network:
    driver: bridge
