/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionRequestSystemMessageContent : The contents of the system message.
/// The contents of the system message.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ChatCompletionRequestSystemMessageContent {
    /// The contents of the system message.
    TextContent(String),
    /// An array of content parts with a defined type. For system messages, only type `text` is supported.
    ArrayOfContentParts(Vec<models::ChatCompletionRequestSystemMessageContentPart>),
}

impl Default for ChatCompletionRequestSystemMessageContent {
    fn default() -> Self {
        Self::TextContent(Default::default())
    }
}

