/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RealtimeServerEventErrorError : Details of the error.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RealtimeServerEventErrorError {
    /// The type of error (e.g., \"invalid_request_error\", \"server_error\"). 
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Error code, if any.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// A human-readable error message.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Parameter related to the error, if any.
    #[serde(rename = "param", skip_serializing_if = "Option::is_none")]
    pub param: Option<String>,
    /// The event_id of the client event that caused the error, if applicable. 
    #[serde(rename = "event_id", skip_serializing_if = "Option::is_none")]
    pub event_id: Option<String>,
}

impl RealtimeServerEventErrorError {
    /// Details of the error.
    pub fn new() -> RealtimeServerEventErrorError {
        RealtimeServerEventErrorError {
            r#type: None,
            code: None,
            message: None,
            param: None,
            event_id: None,
        }
    }
}

