/*
 * OpenAI API
 *
 * The OpenAI REST API. Please see https://platform.openai.com/docs/api-reference for more details.
 *
 * The version of the OpenAPI document: 2.3.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ThreadStreamEventOneOf : Occurs when a new [thread](/docs/api-reference/threads/object) is created.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadStreamEventOneOf {
    /// Whether to enable input audio transcription.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "event")]
    pub event: Event,
    #[serde(rename = "data")]
    pub data: Box<models::ThreadObject>,
}

impl ThreadStreamEventOneOf {
    /// Occurs when a new [thread](/docs/api-reference/threads/object) is created.
    pub fn new(event: Event, data: models::ThreadObject) -> ThreadStreamEventOneOf {
        ThreadStreamEventOneOf {
            enabled: None,
            event,
            data: Box::new(data),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Event {
    #[serde(rename = "thread.created")]
    ThreadPeriodCreated,
}

impl Default for Event {
    fn default() -> Event {
        Self::ThreadPeriodCreated
    }
}

