/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

/// AddUploadPartRequest : The multipart/form-data request body of a data part addition request for an upload.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddUploadPartRequest {
    /// The chunk of bytes for this Part.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "data")]
    pub data: Vec<u8>,
}

impl AddUploadPartRequest {
    /// The multipart/form-data request body of a data part addition request for an upload.
    pub fn new(data: Vec<u8>) -> AddUploadPartRequest {
        AddUploadPartRequest {
            data,
        }
    }
}

