/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

/// AudioTranslationOptions : The configuration information for an audio translation request.
#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AudioTranslationOptions {
    /// The audio data to translate. This must be the binary content of a file in one of the supported media formats:  flac, mp3, mp4, mpeg, mpga, m4a, ogg, wav, webm.
    #[serde_as(as = "serde_with::base64::Base64")]
    #[serde(rename = "file")]
    pub file: Vec<u8>,
    /// The optional filename or descriptive identifier to associate with with the audio data.
    #[serde(rename = "filename", skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(rename = "response_format", skip_serializing_if = "Option::is_none")]
    pub response_format: Option<models::AudioTranslationFormat>,
    /// An optional hint to guide the model's style or continue from a prior audio segment. The written language of the prompt should match the primary spoken language of the audio data.
    #[serde(rename = "prompt", skip_serializing_if = "Option::is_none")]
    pub prompt: Option<String>,
    /// The sampling temperature, between 0 and 1. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. If set to 0, the model will use log probability to automatically increase the temperature until certain thresholds are hit.
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,
    /// The model to use for this translation request.
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
}

impl AudioTranslationOptions {
    /// The configuration information for an audio translation request.
    pub fn new(file: Vec<u8>) -> AudioTranslationOptions {
        AudioTranslationOptions {
            file,
            filename: None,
            response_format: None,
            prompt: None,
            temperature: None,
            model: None,
        }
    }
}

