/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AudioTranslationFormat : Defines available options for the underlying response format of output translation information.
/// Defines available options for the underlying response format of output translation information.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AudioTranslationFormat {
    #[serde(rename = "json")]
    Json,
    #[serde(rename = "verbose_json")]
    VerboseJson,
    #[serde(rename = "text")]
    Text,
    #[serde(rename = "srt")]
    Srt,
    #[serde(rename = "vtt")]
    Vtt,

}

impl std::fmt::Display for AudioTranslationFormat {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Json => write!(f, "json"),
            Self::VerboseJson => write!(f, "verbose_json"),
            Self::Text => write!(f, "text"),
            Self::Srt => write!(f, "srt"),
            Self::Vtt => write!(f, "vtt"),
        }
    }
}

impl Default for AudioTranslationFormat {
    fn default() -> AudioTranslationFormat {
        Self::Json
    }
}

