/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AudioTranscriptionWord : Extended information about a single transcribed word, as provided on responses when the 'word' timestamp granularity is provided.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AudioTranscriptionWord {
    /// The textual content of the word.
    #[serde(rename = "word")]
    pub word: String,
    /// The start time of the word relative to the beginning of the audio, expressed in seconds.
    #[serde(rename = "start")]
    pub start: f32,
    /// The end time of the word relative to the beginning of the audio, expressed in seconds.
    #[serde(rename = "end")]
    pub end: f32,
}

impl AudioTranscriptionWord {
    /// Extended information about a single transcribed word, as provided on responses when the 'word' timestamp granularity is provided.
    pub fn new(word: String, start: f32, end: f32) -> AudioTranscriptionWord {
        AudioTranscriptionWord {
            word,
            start,
            end,
        }
    }
}

