/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AudioTranscriptionTimestampGranularity : Defines the timestamp granularities that can be requested on a verbose transcription response.
/// Defines the timestamp granularities that can be requested on a verbose transcription response.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AudioTranscriptionTimestampGranularity {
    #[serde(rename = "word")]
    Word,
    #[serde(rename = "segment")]
    Segment,

}

impl std::fmt::Display for AudioTranscriptionTimestampGranularity {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Word => write!(f, "word"),
            Self::Segment => write!(f, "segment"),
        }
    }
}

impl Default for AudioTranscriptionTimestampGranularity {
    fn default() -> AudioTranscriptionTimestampGranularity {
        Self::Word
    }
}

