/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AudioTranscriptionSegment : Extended information about a single segment of transcribed audio data. Segments generally represent roughly 5-10 seconds of speech. Segment boundaries typically occur between words but not necessarily sentences.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AudioTranscriptionSegment {
    /// The 0-based index of this segment within a transcription.
    #[serde(rename = "id")]
    pub id: i32,
    /// The time at which this segment started relative to the beginning of the transcribed audio.
    #[serde(rename = "start")]
    pub start: f32,
    /// The time at which this segment ended relative to the beginning of the transcribed audio.
    #[serde(rename = "end")]
    pub end: f32,
    /// The transcribed text that was part of this audio segment.
    #[serde(rename = "text")]
    pub text: String,
    /// The temperature score associated with this audio segment.
    #[serde(rename = "temperature")]
    pub temperature: f32,
    /// The average log probability associated with this audio segment.
    #[serde(rename = "avg_logprob")]
    pub avg_logprob: f32,
    /// The compression ratio of this audio segment.
    #[serde(rename = "compression_ratio")]
    pub compression_ratio: f32,
    /// The probability of no speech detection within this audio segment.
    #[serde(rename = "no_speech_prob")]
    pub no_speech_prob: f32,
    /// The token IDs matching the transcribed text in this audio segment.
    #[serde(rename = "tokens")]
    pub tokens: Vec<i32>,
    /// The seek position associated with the processing of this audio segment. Seek positions are expressed as hundredths of seconds. The model may process several segments from a single seek position, so while the seek position will never represent a later time than the segment's start, the segment's start may represent a significantly later time than the segment's associated seek position.
    #[serde(rename = "seek")]
    pub seek: i32,
}

impl AudioTranscriptionSegment {
    /// Extended information about a single segment of transcribed audio data. Segments generally represent roughly 5-10 seconds of speech. Segment boundaries typically occur between words but not necessarily sentences.
    pub fn new(id: i32, start: f32, end: f32, text: String, temperature: f32, avg_logprob: f32, compression_ratio: f32, no_speech_prob: f32, tokens: Vec<i32>, seek: i32) -> AudioTranscriptionSegment {
        AudioTranscriptionSegment {
            id,
            start,
            end,
            text,
            temperature,
            avg_logprob,
            compression_ratio,
            no_speech_prob,
            tokens,
            seek,
        }
    }
}

