/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AudioTaskLabel : Defines the possible descriptors for available audio operation responses.
/// Defines the possible descriptors for available audio operation responses.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AudioTaskLabel {
    #[serde(rename = "transcribe")]
    Transcribe,
    #[serde(rename = "translate")]
    Translate,

}

impl std::fmt::Display for AudioTaskLabel {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Transcribe => write!(f, "transcribe"),
            Self::Translate => write!(f, "translate"),
        }
    }
}

impl Default for AudioTaskLabel {
    fn default() -> AudioTaskLabel {
        Self::Transcribe
    }
}

