/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureSearchQueryType : The type of Azure Search retrieval query that should be executed when using it as an Azure OpenAI chat extension.
/// The type of Azure Search retrieval query that should be executed when using it as an Azure OpenAI chat extension.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AzureSearchQueryType {
    #[serde(rename = "simple")]
    Simple,
    #[serde(rename = "semantic")]
    Semantic,
    #[serde(rename = "vector")]
    Vector,
    #[serde(rename = "vector_simple_hybrid")]
    VectorSimpleHybrid,
    #[serde(rename = "vector_semantic_hybrid")]
    VectorSemanticHybrid,

}

impl std::fmt::Display for AzureSearchQueryType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Simple => write!(f, "simple"),
            Self::Semantic => write!(f, "semantic"),
            Self::Vector => write!(f, "vector"),
            Self::VectorSimpleHybrid => write!(f, "vector_simple_hybrid"),
            Self::VectorSemanticHybrid => write!(f, "vector_semantic_hybrid"),
        }
    }
}

impl Default for AzureSearchQueryType {
    fn default() -> AzureSearchQueryType {
        Self::Simple
    }
}

