/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureChatExtensionRetrievedDocument : The retrieved document.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureChatExtensionRetrievedDocument {
    /// The content of the citation.
    #[serde(rename = "content")]
    pub content: String,
    /// The title of the citation.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The URL of the citation.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The file path of the citation.
    #[serde(rename = "filepath", skip_serializing_if = "Option::is_none")]
    pub filepath: Option<String>,
    /// The chunk ID of the citation.
    #[serde(rename = "chunk_id", skip_serializing_if = "Option::is_none")]
    pub chunk_id: Option<String>,
    /// The rerank score of the retrieved document.
    #[serde(rename = "rerank_score", skip_serializing_if = "Option::is_none")]
    pub rerank_score: Option<f64>,
    /// The search queries used to retrieve the document.
    #[serde(rename = "search_queries")]
    pub search_queries: Vec<String>,
    /// The index of the data source.
    #[serde(rename = "data_source_index")]
    pub data_source_index: i32,
    /// The original search score of the retrieved document.
    #[serde(rename = "original_search_score", skip_serializing_if = "Option::is_none")]
    pub original_search_score: Option<f64>,
    #[serde(rename = "filter_reason", skip_serializing_if = "Option::is_none")]
    pub filter_reason: Option<models::AzureChatExtensionRetrieveDocumentFilterReason>,
}

impl AzureChatExtensionRetrievedDocument {
    /// The retrieved document.
    pub fn new(content: String, search_queries: Vec<String>, data_source_index: i32) -> AzureChatExtensionRetrievedDocument {
        AzureChatExtensionRetrievedDocument {
            content,
            title: None,
            url: None,
            filepath: None,
            chunk_id: None,
            rerank_score: None,
            search_queries,
            data_source_index,
            original_search_score: None,
            filter_reason: None,
        }
    }
}

