/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureChatExtensionConfiguration :   A representation of configuration data for a single Azure OpenAI chat extension. This will be used by a chat   completions request that should use Azure OpenAI chat extensions to augment the response behavior.   The use of this configuration is compatible only with Azure OpenAI.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum AzureChatExtensionConfiguration {
    #[serde(rename="AzureCosmosDBChatExtensionConfiguration")]
    AzureCosmosDbChatExtensionConfiguration {
    },
    #[serde(rename="AzureSearchChatExtensionConfiguration")]
    AzureSearchChatExtensionConfiguration {
    },
    #[serde(rename="ElasticsearchChatExtensionConfiguration")]
    ElasticsearchChatExtensionConfiguration {
    },
    #[serde(rename="MongoDBChatExtensionConfiguration")]
    MongoDbChatExtensionConfiguration {
    },
    #[serde(rename="PineconeChatExtensionConfiguration")]
    PineconeChatExtensionConfiguration {
    },
}

impl Default for AzureChatExtensionConfiguration {
    fn default() -> Self {
        Self::AzureCosmosDbChatExtensionConfiguration {
        }
        
    }
}


