/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureChatExtensionDataSourceResponseCitation : A single instance of additional context information available when Azure OpenAI chat extensions are involved in the generation of a corresponding chat completions response. This context information is only populated when using an Azure OpenAI request configured to use a matching extension.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureChatExtensionDataSourceResponseCitation {
    /// The content of the citation.
    #[serde(rename = "content")]
    pub content: String,
    /// The title of the citation.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// The URL of the citation.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The file path of the citation.
    #[serde(rename = "filepath", skip_serializing_if = "Option::is_none")]
    pub filepath: Option<String>,
    /// The chunk ID of the citation.
    #[serde(rename = "chunk_id", skip_serializing_if = "Option::is_none")]
    pub chunk_id: Option<String>,
    /// The rerank score of the retrieved document.
    #[serde(rename = "rerank_score", skip_serializing_if = "Option::is_none")]
    pub rerank_score: Option<f64>,
}

impl AzureChatExtensionDataSourceResponseCitation {
    /// A single instance of additional context information available when Azure OpenAI chat extensions are involved in the generation of a corresponding chat completions response. This context information is only populated when using an Azure OpenAI request configured to use a matching extension.
    pub fn new(content: String) -> AzureChatExtensionDataSourceResponseCitation {
        AzureChatExtensionDataSourceResponseCitation {
            content,
            title: None,
            url: None,
            filepath: None,
            chunk_id: None,
            rerank_score: None,
        }
    }
}

