/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureCosmosDbFieldMappingOptions : Optional settings to control how fields are processed when using a configured Azure Cosmos DB resource.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureCosmosDbFieldMappingOptions {
    /// The name of the index field to use as a title.
    #[serde(rename = "title_field", skip_serializing_if = "Option::is_none")]
    pub title_field: Option<String>,
    /// The name of the index field to use as a URL.
    #[serde(rename = "url_field", skip_serializing_if = "Option::is_none")]
    pub url_field: Option<String>,
    /// The name of the index field to use as a filepath.
    #[serde(rename = "filepath_field", skip_serializing_if = "Option::is_none")]
    pub filepath_field: Option<String>,
    /// The names of index fields that should be treated as content.
    #[serde(rename = "content_fields")]
    pub content_fields: Vec<String>,
    /// The separator pattern that content fields should use.
    #[serde(rename = "content_fields_separator", skip_serializing_if = "Option::is_none")]
    pub content_fields_separator: Option<String>,
    /// The names of fields that represent vector data.
    #[serde(rename = "vector_fields")]
    pub vector_fields: Vec<String>,
}

impl AzureCosmosDbFieldMappingOptions {
    /// Optional settings to control how fields are processed when using a configured Azure Cosmos DB resource.
    pub fn new(content_fields: Vec<String>, vector_fields: Vec<String>) -> AzureCosmosDbFieldMappingOptions {
        AzureCosmosDbFieldMappingOptions {
            title_field: None,
            url_field: None,
            filepath_field: None,
            content_fields,
            content_fields_separator: None,
            vector_fields,
        }
    }
}

