/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzurePeriodCorePeriodFoundationsPeriodErrorResponse : A response containing error details.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzurePeriodCorePeriodFoundationsPeriodErrorResponse {
    #[serde(rename = "error")]
    pub error: Box<models::AzurePeriodCorePeriodFoundationsPeriodError>,
}

impl AzurePeriodCorePeriodFoundationsPeriodErrorResponse {
    /// A response containing error details.
    pub fn new(error: models::AzurePeriodCorePeriodFoundationsPeriodError) -> AzurePeriodCorePeriodFoundationsPeriodErrorResponse {
        AzurePeriodCorePeriodFoundationsPeriodErrorResponse {
            error: Box::new(error),
        }
    }
}

