/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureCosmosDbChatExtensionConfiguration : A specific representation of configurable options for Azure Cosmos DB when using it as an Azure OpenAI chat extension.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureCosmosDbChatExtensionConfiguration {
    #[serde(rename = "parameters")]
    pub parameters: Box<models::AzureCosmosDbChatExtensionParameters>,
    #[serde(rename = "type")]
    pub r#type: models::AzureChatExtensionType,
}

impl AzureCosmosDbChatExtensionConfiguration {
    /// A specific representation of configurable options for Azure Cosmos DB when using it as an Azure OpenAI chat extension.
    pub fn new(parameters: models::AzureCosmosDbChatExtensionParameters, r#type: models::AzureChatExtensionType) -> AzureCosmosDbChatExtensionConfiguration {
        AzureCosmosDbChatExtensionConfiguration {
            parameters: Box::new(parameters),
            r#type,
        }
    }
}

