/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureChatExtensionRetrieveDocumentFilterReason : The reason for filtering the retrieved document.
/// The reason for filtering the retrieved document.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AzureChatExtensionRetrieveDocumentFilterReason {
    #[serde(rename = "score")]
    Score,
    #[serde(rename = "rerank")]
    Rerank,

}

impl std::fmt::Display for AzureChatExtensionRetrieveDocumentFilterReason {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Score => write!(f, "score"),
            Self::Rerank => write!(f, "rerank"),
        }
    }
}

impl Default for AzureChatExtensionRetrieveDocumentFilterReason {
    fn default() -> AzureChatExtensionRetrieveDocumentFilterReason {
        Self::Score
    }
}

