/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureSearchChatExtensionConfiguration : A specific representation of configurable options for Azure Search when using it as an Azure OpenAI chat extension.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureSearchChatExtensionConfiguration {
    #[serde(rename = "parameters")]
    pub parameters: Box<models::AzureSearchChatExtensionParameters>,
    #[serde(rename = "type")]
    pub r#type: models::AzureChatExtensionType,
}

impl AzureSearchChatExtensionConfiguration {
    /// A specific representation of configurable options for Azure Search when using it as an Azure OpenAI chat extension.
    pub fn new(parameters: models::AzureSearchChatExtensionParameters, r#type: models::AzureChatExtensionType) -> AzureSearchChatExtensionConfiguration {
        AzureSearchChatExtensionConfiguration {
            parameters: Box::new(parameters),
            r#type,
        }
    }
}

