/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureChatExtensionType :   A representation of configuration data for a single Azure OpenAI chat extension. This will be used by a chat   completions request that should use Azure OpenAI chat extensions to augment the response behavior.   The use of this configuration is compatible only with Azure OpenAI.
///   A representation of configuration data for a single Azure OpenAI chat extension. This will be used by a chat   completions request that should use Azure OpenAI chat extensions to augment the response behavior.   The use of this configuration is compatible only with Azure OpenAI.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AzureChatExtensionType {
    #[serde(rename = "azure_search")]
    AzureSearch,
    #[serde(rename = "azure_ml_index")]
    AzureMlIndex,
    #[serde(rename = "azure_cosmos_db")]
    AzureCosmosDb,
    #[serde(rename = "elasticsearch")]
    Elasticsearch,
    #[serde(rename = "pinecone")]
    Pinecone,

}

impl std::fmt::Display for AzureChatExtensionType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AzureSearch => write!(f, "azure_search"),
            Self::AzureMlIndex => write!(f, "azure_ml_index"),
            Self::AzureCosmosDb => write!(f, "azure_cosmos_db"),
            Self::Elasticsearch => write!(f, "elasticsearch"),
            Self::Pinecone => write!(f, "pinecone"),
        }
    }
}

impl Default for AzureChatExtensionType {
    fn default() -> AzureChatExtensionType {
        Self::AzureSearch
    }
}

