/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureGroundingEnhancementLine : A content line object consisting of an adjacent sequence of content elements, such as words and selection marks.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureGroundingEnhancementLine {
    /// The text within the line.
    #[serde(rename = "text")]
    pub text: String,
    /// An array of spans that represent detected objects and its bounding box information.
    #[serde(rename = "spans")]
    pub spans: Vec<models::AzureGroundingEnhancementLineSpan>,
}

impl AzureGroundingEnhancementLine {
    /// A content line object consisting of an adjacent sequence of content elements, such as words and selection marks.
    pub fn new(text: String, spans: Vec<models::AzureGroundingEnhancementLineSpan>) -> AzureGroundingEnhancementLine {
        AzureGroundingEnhancementLine {
            text,
            spans,
        }
    }
}

