/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureSearchIndexFieldMappingOptions : Optional settings to control how fields are processed when using a configured Azure Search resource.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureSearchIndexFieldMappingOptions {
    /// The name of the index field to use as a title.
    #[serde(rename = "title_field", skip_serializing_if = "Option::is_none")]
    pub title_field: Option<String>,
    /// The name of the index field to use as a URL.
    #[serde(rename = "url_field", skip_serializing_if = "Option::is_none")]
    pub url_field: Option<String>,
    /// The name of the index field to use as a filepath.
    #[serde(rename = "filepath_field", skip_serializing_if = "Option::is_none")]
    pub filepath_field: Option<String>,
    /// The names of index fields that should be treated as content.
    #[serde(rename = "content_fields", skip_serializing_if = "Option::is_none")]
    pub content_fields: Option<Vec<String>>,
    /// The separator pattern that content fields should use.
    #[serde(rename = "content_fields_separator", skip_serializing_if = "Option::is_none")]
    pub content_fields_separator: Option<String>,
    /// The names of fields that represent vector data.
    #[serde(rename = "vector_fields", skip_serializing_if = "Option::is_none")]
    pub vector_fields: Option<Vec<String>>,
    /// The names of fields that represent image vector data.
    #[serde(rename = "image_vector_fields", skip_serializing_if = "Option::is_none")]
    pub image_vector_fields: Option<Vec<String>>,
}

impl AzureSearchIndexFieldMappingOptions {
    /// Optional settings to control how fields are processed when using a configured Azure Search resource.
    pub fn new() -> AzureSearchIndexFieldMappingOptions {
        AzureSearchIndexFieldMappingOptions {
            title_field: None,
            url_field: None,
            filepath_field: None,
            content_fields: None,
            content_fields_separator: None,
            vector_fields: None,
            image_vector_fields: None,
        }
    }
}

