/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureChatOcrEnhancementConfiguration : A representation of the available options for the Azure OpenAI optical character recognition (OCR) enhancement.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureChatOcrEnhancementConfiguration {
    /// Specifies whether the enhancement is enabled.
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl AzureChatOcrEnhancementConfiguration {
    /// A representation of the available options for the Azure OpenAI optical character recognition (OCR) enhancement.
    pub fn new(enabled: bool) -> AzureChatOcrEnhancementConfiguration {
        AzureChatOcrEnhancementConfiguration {
            enabled,
        }
    }
}

