/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzurePeriodCorePeriodFoundationsPeriodInnerError : An object containing more specific information about the error. As per Microsoft One API guidelines - https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzurePeriodCorePeriodFoundationsPeriodInnerError {
    /// One of a server-defined set of error codes.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    #[serde(rename = "innererror", skip_serializing_if = "Option::is_none")]
    pub innererror: Option<Box<models::AzurePeriodCorePeriodFoundationsPeriodInnerError>>,
}

impl AzurePeriodCorePeriodFoundationsPeriodInnerError {
    /// An object containing more specific information about the error. As per Microsoft One API guidelines - https://github.com/Microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses.
    pub fn new() -> AzurePeriodCorePeriodFoundationsPeriodInnerError {
        AzurePeriodCorePeriodFoundationsPeriodInnerError {
            code: None,
            innererror: None,
        }
    }
}

