/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureGroundingEnhancementCoordinatePoint : A representation of a single polygon point as used by the Azure grounding enhancement.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureGroundingEnhancementCoordinatePoint {
    /// The x-coordinate (horizontal axis) of the point.
    #[serde(rename = "x")]
    pub x: f32,
    /// The y-coordinate (vertical axis) of the point.
    #[serde(rename = "y")]
    pub y: f32,
}

impl AzureGroundingEnhancementCoordinatePoint {
    /// A representation of a single polygon point as used by the Azure grounding enhancement.
    pub fn new(x: f32, y: f32) -> AzureGroundingEnhancementCoordinatePoint {
        AzureGroundingEnhancementCoordinatePoint {
            x,
            y,
        }
    }
}

