/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureChatGroundingEnhancementConfiguration : A representation of the available options for the Azure OpenAI grounding enhancement.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureChatGroundingEnhancementConfiguration {
    /// Specifies whether the enhancement is enabled.
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl AzureChatGroundingEnhancementConfiguration {
    /// A representation of the available options for the Azure OpenAI grounding enhancement.
    pub fn new(enabled: bool) -> AzureChatGroundingEnhancementConfiguration {
        AzureChatGroundingEnhancementConfiguration {
            enabled,
        }
    }
}

