/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureChatExtensionsMessageContext :   A representation of the additional context information available when Azure OpenAI chat extensions are involved   in the generation of a corresponding chat completions response. This context information is only populated when   using an Azure OpenAI request configured to use a matching extension.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureChatExtensionsMessageContext {
    ///   The contextual information associated with the Azure chat extensions used for a chat completions request.   These messages describe the data source retrievals, plugin invocations, and other intermediate steps taken in the   course of generating a chat completions response that was augmented by capabilities from Azure OpenAI chat   extensions.
    #[serde(rename = "citations", skip_serializing_if = "Option::is_none")]
    pub citations: Option<Vec<models::AzureChatExtensionDataSourceResponseCitation>>,
    /// The detected intent from the chat history, used to pass to the next turn to carry over the context.
    #[serde(rename = "intent", skip_serializing_if = "Option::is_none")]
    pub intent: Option<String>,
    /// All the retrieved documents.
    #[serde(rename = "all_retrieved_documents", skip_serializing_if = "Option::is_none")]
    pub all_retrieved_documents: Option<Vec<models::AzureChatExtensionRetrievedDocument>>,
}

impl AzureChatExtensionsMessageContext {
    ///   A representation of the additional context information available when Azure OpenAI chat extensions are involved   in the generation of a corresponding chat completions response. This context information is only populated when   using an Azure OpenAI request configured to use a matching extension.
    pub fn new() -> AzureChatExtensionsMessageContext {
        AzureChatExtensionsMessageContext {
            citations: None,
            intent: None,
            all_retrieved_documents: None,
        }
    }
}

