/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureMachineLearningIndexChatExtensionConfiguration : A specific representation of configurable options for Azure Machine Learning vector index when using it as an Azure OpenAI chat extension.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureMachineLearningIndexChatExtensionConfiguration {
    #[serde(rename = "parameters")]
    pub parameters: Box<models::AzureMachineLearningIndexChatExtensionParameters>,
    #[serde(rename = "type")]
    pub r#type: models::AzureChatExtensionType,
}

impl AzureMachineLearningIndexChatExtensionConfiguration {
    /// A specific representation of configurable options for Azure Machine Learning vector index when using it as an Azure OpenAI chat extension.
    pub fn new(parameters: models::AzureMachineLearningIndexChatExtensionParameters, r#type: models::AzureChatExtensionType) -> AzureMachineLearningIndexChatExtensionConfiguration {
        AzureMachineLearningIndexChatExtensionConfiguration {
            parameters: Box::new(parameters),
            r#type,
        }
    }
}

