/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureChatEnhancements : Represents the output results of Azure enhancements to chat completions, as configured via the matching input provided in the request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureChatEnhancements {
    #[serde(rename = "grounding", skip_serializing_if = "Option::is_none")]
    pub grounding: Option<Box<models::AzureGroundingEnhancement>>,
}

impl AzureChatEnhancements {
    /// Represents the output results of Azure enhancements to chat completions, as configured via the matching input provided in the request.
    pub fn new() -> AzureChatEnhancements {
        AzureChatEnhancements {
            grounding: None,
        }
    }
}

