/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureChatEnhancementConfiguration : A representation of the available Azure OpenAI enhancement configurations.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureChatEnhancementConfiguration {
    #[serde(rename = "grounding", skip_serializing_if = "Option::is_none")]
    pub grounding: Option<Box<models::AzureChatGroundingEnhancementConfiguration>>,
    #[serde(rename = "ocr", skip_serializing_if = "Option::is_none")]
    pub ocr: Option<Box<models::AzureChatOcrEnhancementConfiguration>>,
}

impl AzureChatEnhancementConfiguration {
    /// A representation of the available Azure OpenAI enhancement configurations.
    pub fn new() -> AzureChatEnhancementConfiguration {
        AzureChatEnhancementConfiguration {
            grounding: None,
            ocr: None,
        }
    }
}

