/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureGroundingEnhancementLineSpan : A span object that represents a detected object and its bounding box information.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureGroundingEnhancementLineSpan {
    /// The text content of the span that represents the detected object.
    #[serde(rename = "text")]
    pub text: String,
    /// The character offset within the text where the span begins. This offset is defined as the position of the first character of the span, counting from the start of the text as Unicode codepoints.
    #[serde(rename = "offset")]
    pub offset: i32,
    /// The length of the span in characters, measured in Unicode codepoints.
    #[serde(rename = "length")]
    pub length: i32,
    /// An array of objects representing points in the polygon that encloses the detected object.
    #[serde(rename = "polygon")]
    pub polygon: Vec<models::AzureGroundingEnhancementCoordinatePoint>,
}

impl AzureGroundingEnhancementLineSpan {
    /// A span object that represents a detected object and its bounding box information.
    pub fn new(text: String, offset: i32, length: i32, polygon: Vec<models::AzureGroundingEnhancementCoordinatePoint>) -> AzureGroundingEnhancementLineSpan {
        AzureGroundingEnhancementLineSpan {
            text,
            offset,
            length,
            polygon,
        }
    }
}

