/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AzureGroundingEnhancement : The grounding enhancement that returns the bounding box of the objects detected in the image.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AzureGroundingEnhancement {
    /// The lines of text detected by the grounding enhancement.
    #[serde(rename = "lines")]
    pub lines: Vec<models::AzureGroundingEnhancementLine>,
}

impl AzureGroundingEnhancement {
    /// The grounding enhancement that returns the bounding box of the objects detected in the image.
    pub fn new(lines: Vec<models::AzureGroundingEnhancementLine>) -> AzureGroundingEnhancement {
        AzureGroundingEnhancement {
            lines,
        }
    }
}

