/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchCreateRequest : Defines the request to create a batch.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchCreateRequest {
    /// The API endpoint used by the batch.
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    /// The ID of the input file for the batch.
    #[serde(rename = "input_file_id")]
    pub input_file_id: String,
    /// The time frame within which the batch should be processed.
    #[serde(rename = "completion_window")]
    pub completion_window: String,
    /// A set of key-value pairs that can be attached to the batch. This can be useful for storing additional information about the batch in a structured format.
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
}

impl BatchCreateRequest {
    /// Defines the request to create a batch.
    pub fn new(endpoint: String, input_file_id: String, completion_window: String) -> BatchCreateRequest {
        BatchCreateRequest {
            endpoint,
            input_file_id,
            completion_window,
            metadata: None,
        }
    }
}

