/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchErrorDatum : A Datum containing information about a Batch Error.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchErrorDatum {
    /// An error code identifying the error type.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// A human-readable message providing more details about the error.
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// The name of the parameter that caused the error, if applicable.
    #[serde(rename = "param", skip_serializing_if = "Option::is_none")]
    pub param: Option<String>,
    /// The line number of the input file where the error occurred, if applicable.
    #[serde(rename = "line", skip_serializing_if = "Option::is_none")]
    pub line: Option<i32>,
}

impl BatchErrorDatum {
    /// A Datum containing information about a Batch Error.
    pub fn new() -> BatchErrorDatum {
        BatchErrorDatum {
            code: None,
            message: None,
            param: None,
            line: None,
        }
    }
}

