/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchRequestCounts : The request counts for different statuses within the batch.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchRequestCounts {
    /// Total number of requests in the batch.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,
    /// Number of requests that have been completed successfully.
    #[serde(rename = "completed", skip_serializing_if = "Option::is_none")]
    pub completed: Option<i32>,
    /// Number of requests that have failed.
    #[serde(rename = "failed", skip_serializing_if = "Option::is_none")]
    pub failed: Option<i32>,
}

impl BatchRequestCounts {
    /// The request counts for different statuses within the batch.
    pub fn new() -> BatchRequestCounts {
        BatchRequestCounts {
            total: None,
            completed: None,
            failed: None,
        }
    }
}

