/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionsTextResponseFormat : The standard Chat Completions response format that can freely generate text and is not guaranteed to produce response content that adheres to a specific schema.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionsTextResponseFormat {
    /// The discriminated type for the response format.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ChatCompletionsTextResponseFormat {
    /// The standard Chat Completions response format that can freely generate text and is not guaranteed to produce response content that adheres to a specific schema.
    pub fn new(r#type: String) -> ChatCompletionsTextResponseFormat {
        ChatCompletionsTextResponseFormat {
            r#type,
        }
    }
}

