/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatRequestMessage : An abstract representation of a chat message as provided in a request.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "role")]
pub enum ChatRequestMessage {
    #[serde(rename="ChatRequestAssistantMessage")]
    ChatRequestAssistantMessage {
    },
    #[serde(rename="ChatRequestFunctionMessage")]
    ChatRequestFunctionMessage {
    },
    #[serde(rename="ChatRequestSystemMessage")]
    ChatRequestSystemMessage {
    },
    #[serde(rename="ChatRequestToolMessage")]
    ChatRequestToolMessage {
    },
    #[serde(rename="ChatRequestUserMessage")]
    ChatRequestUserMessage {
    },
}

impl Default for ChatRequestMessage {
    fn default() -> Self {
        Self::ChatRequestAssistantMessage {
        }
        
    }
}


