/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionsResponseFormat : An abstract representation of a response format configuration usable by Chat Completions. Can be used to enable JSON mode.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ChatCompletionsResponseFormat {
    #[serde(rename="ChatCompletionsJsonResponseFormat")]
    ChatCompletionsJsonResponseFormat {
    },
    #[serde(rename="ChatCompletionsTextResponseFormat")]
    ChatCompletionsTextResponseFormat {
    },
}

impl Default for ChatCompletionsResponseFormat {
    fn default() -> Self {
        Self::ChatCompletionsJsonResponseFormat {
        }
        
    }
}


