/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatRequestSystemMessage : A request chat message containing system instructions that influence how the model will generate a chat completions response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatRequestSystemMessage {
    /// The contents of the system message.
    #[serde(rename = "content")]
    pub content: serde_json::Value,
    /// An optional name for the participant.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "role")]
    pub role: models::ChatRole,
}

impl ChatRequestSystemMessage {
    /// A request chat message containing system instructions that influence how the model will generate a chat completions response.
    pub fn new(content: serde_json::Value, role: models::ChatRole) -> ChatRequestSystemMessage {
        ChatRequestSystemMessage {
            content,
            name: None,
            role,
        }
    }
}

