/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionsJsonSchemaResponseFormat : A response format for Chat Completions that restricts responses to emitting JSON that conforms to a provided JSON Schema for Structured Outputs.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionsJsonSchemaResponseFormat {
    #[serde(rename = "json_schema")]
    pub json_schema: Box<serde_json::Value>,
    /// The discriminated type for the response format.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ChatCompletionsJsonSchemaResponseFormat {
    /// A response format for Chat Completions that restricts responses to emitting JSON that conforms to a provided JSON Schema for Structured Outputs.
    pub fn new(json_schema: serde_json::Value, r#type: String) -> ChatCompletionsJsonSchemaResponseFormat {
        ChatCompletionsJsonSchemaResponseFormat {
            json_schema: Box::new(json_schema),
            r#type,
        }
    }
}

