/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatRequestFunctionMessage : A request chat message representing requested output from a configured function.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatRequestFunctionMessage {
    /// The name of the function that was called to produce output.
    #[serde(rename = "name")]
    pub name: String,
    /// The output of the function as requested by the function call.
    #[serde(rename = "content", deserialize_with = "Option::deserialize")]
    pub content: Option<String>,
    #[serde(rename = "role")]
    pub role: models::ChatRole,
}

impl ChatRequestFunctionMessage {
    /// A request chat message representing requested output from a configured function.
    pub fn new(name: String, content: Option<String>, role: models::ChatRole) -> ChatRequestFunctionMessage {
        ChatRequestFunctionMessage {
            name,
            content,
            role,
        }
    }
}

