/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatRole : A description of the intended purpose of a message within a chat completions interaction.
/// A description of the intended purpose of a message within a chat completions interaction.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ChatRole {
    #[serde(rename = "system")]
    System,
    #[serde(rename = "assistant")]
    Assistant,
    #[serde(rename = "user")]
    User,
    #[serde(rename = "function")]
    Function,
    #[serde(rename = "tool")]
    Tool,

}

impl std::fmt::Display for ChatRole {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::System => write!(f, "system"),
            Self::Assistant => write!(f, "assistant"),
            Self::User => write!(f, "user"),
            Self::Function => write!(f, "function"),
            Self::Tool => write!(f, "tool"),
        }
    }
}

impl Default for ChatRole {
    fn default() -> ChatRole {
        Self::System
    }
}

