/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionsOptions : The configuration information for a chat completions request. Completions support a wide variety of tasks and generate text that continues from or \"completes\" provided prompt data.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionsOptions {
    /// The collection of context messages associated with this chat completions request. Typical usage begins with a chat message for the System role that provides instructions for the behavior of the assistant, followed by alternating messages between the User and Assistant roles.
    #[serde(rename = "messages")]
    pub messages: Vec<models::ChatRequestMessage>,
    /// A list of functions the model may generate JSON inputs for.
    #[serde(rename = "functions", skip_serializing_if = "Option::is_none")]
    pub functions: Option<Vec<models::FunctionDefinition>>,
    /// Controls how the model responds to function calls. \"none\" means the model does not call a function, and responds to the end-user. \"auto\" means the model can pick between an end-user or calling a function.  Specifying a particular function via `{\"name\": \"my_function\"}` forces the model to call that function.  \"none\" is the default when no functions are present. \"auto\" is the default if functions are present.
    #[serde(rename = "function_call", skip_serializing_if = "Option::is_none")]
    pub function_call: Option<serde_json::Value>,
    /// The maximum number of tokens allowed for the generated answer. By default, the number of tokens the model can return will be (4096 - prompt tokens).  This value is now deprecated in favor of `max_completion_tokens`, and is not compatible with o1 series models.
    #[serde(rename = "max_tokens", skip_serializing_if = "Option::is_none")]
    pub max_tokens: Option<i32>,
    /// The sampling temperature to use that controls the apparent creativity of generated completions. Higher values will make output more random while lower values will make results more focused and deterministic. It is not recommended to modify temperature and top_p for the same completions request as the interaction of these two settings is difficult to predict.
    #[serde(rename = "temperature", skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f32>,
    /// An alternative to sampling with temperature called nucleus sampling. This value causes the model to consider the results of tokens with the provided probability mass. As an example, a value of 0.15 will cause only the tokens comprising the top 15% of probability mass to be considered. It is not recommended to modify temperature and top_p for the same completions request as the interaction of these two settings is difficult to predict.
    #[serde(rename = "top_p", skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f32>,
    /// A map between GPT token IDs and bias scores that influences the probability of specific tokens appearing in a completions response. Token IDs are computed via external tokenizer tools, while bias scores reside in the range of -100 to 100 with minimum and maximum values corresponding to a full ban or exclusive selection of a token, respectively. The exact behavior of a given bias score varies by model.
    #[serde(rename = "logit_bias", skip_serializing_if = "Option::is_none")]
    pub logit_bias: Option<std::collections::HashMap<String, i32>>,
    /// An identifier for the caller or end user of the operation. This may be used for tracking or rate-limiting purposes.
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    /// The number of chat completions choices that should be generated for a chat completions response. Because this setting can generate many completions, it may quickly consume your token quota. Use carefully and ensure reasonable settings for max_tokens and stop.
    #[serde(rename = "n", skip_serializing_if = "Option::is_none")]
    pub n: Option<i32>,
    /// A collection of textual sequences that will end completions generation.
    #[serde(rename = "stop", skip_serializing_if = "Option::is_none")]
    pub stop: Option<Vec<String>>,
    /// A value that influences the probability of generated tokens appearing based on their existing presence in generated text. Positive values will make tokens less likely to appear when they already exist and increase the model's likelihood to output new topics.
    #[serde(rename = "presence_penalty", skip_serializing_if = "Option::is_none")]
    pub presence_penalty: Option<f32>,
    /// A value that influences the probability of generated tokens appearing based on their cumulative frequency in generated text. Positive values will make tokens less likely to appear as their frequency increases and decrease the likelihood of the model repeating the same statements verbatim.
    #[serde(rename = "frequency_penalty", skip_serializing_if = "Option::is_none")]
    pub frequency_penalty: Option<f32>,
    /// A value indicating whether chat completions should be streamed for this request.
    #[serde(rename = "stream", skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,
    /// The model name to provide as part of this completions request. Not applicable to Azure OpenAI, where deployment information should be included in the Azure resource URI that's connected to.
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    ///   The configuration entries for Azure OpenAI chat extensions that use them.   This additional specification is only compatible with Azure OpenAI.
    #[serde(rename = "data_sources", skip_serializing_if = "Option::is_none")]
    pub data_sources: Option<Vec<models::AzureChatExtensionConfiguration>>,
    #[serde(rename = "enhancements", skip_serializing_if = "Option::is_none")]
    pub enhancements: Option<Box<models::AzureChatEnhancementConfiguration>>,
    /// If specified, the system will make a best effort to sample deterministically such that repeated requests with the same seed and parameters should return the same result. Determinism is not guaranteed, and you should refer to the system_fingerprint response parameter to monitor changes in the backend.\"
    #[serde(rename = "seed", skip_serializing_if = "Option::is_none")]
    pub seed: Option<i64>,
    /// Whether to return log probabilities of the output tokens or not. If true, returns the log probabilities of each output token returned in the `content` of `message`. This option is currently not available on the `gpt-4-vision-preview` model.
    #[serde(rename = "logprobs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub logprobs: Option<Option<bool>>,
    /// An integer between 0 and 5 specifying the number of most likely tokens to return at each token position, each with an associated log probability. `logprobs` must be set to `true` if this parameter is used.
    #[serde(rename = "top_logprobs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub top_logprobs: Option<Option<i32>>,
    #[serde(rename = "response_format", skip_serializing_if = "Option::is_none")]
    pub response_format: Option<Box<models::ChatCompletionsResponseFormat>>,
    /// The available tool definitions that the chat completions request can use, including caller-defined functions.
    #[serde(rename = "tools", skip_serializing_if = "Option::is_none")]
    pub tools: Option<Vec<models::ChatCompletionsToolDefinition>>,
    /// If specified, the model will configure which of the provided tools it can use for the chat completions response.
    #[serde(rename = "tool_choice", skip_serializing_if = "Option::is_none")]
    pub tool_choice: Option<serde_json::Value>,
}

impl ChatCompletionsOptions {
    /// The configuration information for a chat completions request. Completions support a wide variety of tasks and generate text that continues from or \"completes\" provided prompt data.
    pub fn new(messages: Vec<models::ChatRequestMessage>) -> ChatCompletionsOptions {
        ChatCompletionsOptions {
            messages,
            functions: None,
            function_call: None,
            max_tokens: None,
            temperature: None,
            top_p: None,
            logit_bias: None,
            user: None,
            n: None,
            stop: None,
            presence_penalty: None,
            frequency_penalty: None,
            stream: None,
            model: None,
            data_sources: None,
            enhancements: None,
            seed: None,
            logprobs: None,
            top_logprobs: None,
            response_format: None,
            tools: None,
            tool_choice: None,
        }
    }
}

