/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionsFunctionToolCall : A tool call to a function tool, issued by the model in evaluation of a configured function tool, that represents a function invocation needed for a subsequent chat completions request to resolve.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionsFunctionToolCall {
    #[serde(rename = "function")]
    pub function: Box<models::FunctionCall>,
    /// The object type.
    #[serde(rename = "type")]
    pub r#type: String,
    /// The ID of the tool call.
    #[serde(rename = "id")]
    pub id: String,
}

impl ChatCompletionsFunctionToolCall {
    /// A tool call to a function tool, issued by the model in evaluation of a configured function tool, that represents a function invocation needed for a subsequent chat completions request to resolve.
    pub fn new(function: models::FunctionCall, r#type: String, id: String) -> ChatCompletionsFunctionToolCall {
        ChatCompletionsFunctionToolCall {
            function: Box::new(function),
            r#type,
            id,
        }
    }
}

