/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionsFunctionToolDefinition : The definition information for a chat completions function tool that can call a function in response to a tool call.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionsFunctionToolDefinition {
    /// The function definition details for the function tool.
    #[serde(rename = "function")]
    pub function: Box<serde_json::Value>,
    /// The object type.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ChatCompletionsFunctionToolDefinition {
    /// The definition information for a chat completions function tool that can call a function in response to a tool call.
    pub fn new(function: serde_json::Value, r#type: String) -> ChatCompletionsFunctionToolDefinition {
        ChatCompletionsFunctionToolDefinition {
            function: Box::new(function),
            r#type,
        }
    }
}

