/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatFinishDetails : An abstract representation of structured information about why a chat completions response terminated.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ChatFinishDetails {
    #[serde(rename="MaxTokensFinishDetails")]
    MaxTokensFinishDetails {
    },
    #[serde(rename="StopFinishDetails")]
    StopFinishDetails {
    },
}

impl Default for ChatFinishDetails {
    fn default() -> Self {
        Self::MaxTokensFinishDetails {
        }
        
    }
}


