/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionsJsonResponseFormat : A response format for Chat Completions that restricts responses to emitting valid JSON objects.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatCompletionsJsonResponseFormat {
    /// The discriminated type for the response format.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl ChatCompletionsJsonResponseFormat {
    /// A response format for Chat Completions that restricts responses to emitting valid JSON objects.
    pub fn new(r#type: String) -> ChatCompletionsJsonResponseFormat {
        ChatCompletionsJsonResponseFormat {
            r#type,
        }
    }
}

