/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionsToolDefinition : An abstract representation of a tool that can be used by the model to improve a chat completions response.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ChatCompletionsToolDefinition {
    #[serde(rename="ChatCompletionsFunctionToolDefinition")]
    ChatCompletionsFunctionToolDefinition {
    },
}

impl Default for ChatCompletionsToolDefinition {
    fn default() -> Self {
        Self::ChatCompletionsFunctionToolDefinition {
        }
        
    }
}


