/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatCompletionsToolCall : An abstract representation of a tool call that must be resolved in a subsequent request to perform the requested chat completion.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum ChatCompletionsToolCall {
    #[serde(rename="ChatCompletionsFunctionToolCall")]
    ChatCompletionsFunctionToolCall {
        /// The ID of the tool call.
        #[serde(rename = "id")]
        id: String,
    },
}

impl Default for ChatCompletionsToolCall {
    fn default() -> Self {
        Self::ChatCompletionsFunctionToolCall {
            id: Default::default(),
        }
        
    }
}


