/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ChatRequestToolMessage : A request chat message representing requested output from a configured tool.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChatRequestToolMessage {
    /// The content of the message.
    #[serde(rename = "content")]
    pub content: serde_json::Value,
    /// The ID of the tool call resolved by the provided content.
    #[serde(rename = "tool_call_id")]
    pub tool_call_id: String,
    #[serde(rename = "role")]
    pub role: models::ChatRole,
}

impl ChatRequestToolMessage {
    /// A request chat message representing requested output from a configured tool.
    pub fn new(content: serde_json::Value, tool_call_id: String, role: models::ChatRole) -> ChatRequestToolMessage {
        ChatRequestToolMessage {
            content,
            tool_call_id,
            role,
        }
    }
}

