/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompletionsUsageCompletionTokensDetails : Breakdown of tokens used in a completion.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionsUsageCompletionTokensDetails {
    /// Tokens generated by the model for reasoning.
    #[serde(rename = "reasoning_tokens", skip_serializing_if = "Option::is_none")]
    pub reasoning_tokens: Option<i32>,
}

impl CompletionsUsageCompletionTokensDetails {
    /// Breakdown of tokens used in a completion.
    pub fn new() -> CompletionsUsageCompletionTokensDetails {
        CompletionsUsageCompletionTokensDetails {
            reasoning_tokens: None,
        }
    }
}

