/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompletionsUsage : Representation of the token counts processed for a completions request. Counts consider all tokens across prompts, choices, choice alternates, best_of generations, and other consumers.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionsUsage {
    /// The number of tokens generated across all completions emissions.
    #[serde(rename = "completion_tokens")]
    pub completion_tokens: i32,
    /// The number of tokens in the provided prompts for the completions request.
    #[serde(rename = "prompt_tokens")]
    pub prompt_tokens: i32,
    /// The total number of tokens processed for the completions request and response.
    #[serde(rename = "total_tokens")]
    pub total_tokens: i32,
    #[serde(rename = "prompt_tokens_details", skip_serializing_if = "Option::is_none")]
    pub prompt_tokens_details: Option<Box<models::CompletionsUsagePromptTokensDetails>>,
    #[serde(rename = "completion_tokens_details", skip_serializing_if = "Option::is_none")]
    pub completion_tokens_details: Option<Box<models::CompletionsUsageCompletionTokensDetails>>,
}

impl CompletionsUsage {
    /// Representation of the token counts processed for a completions request. Counts consider all tokens across prompts, choices, choice alternates, best_of generations, and other consumers.
    pub fn new(completion_tokens: i32, prompt_tokens: i32, total_tokens: i32) -> CompletionsUsage {
        CompletionsUsage {
            completion_tokens,
            prompt_tokens,
            total_tokens,
            prompt_tokens_details: None,
            completion_tokens_details: None,
        }
    }
}

