/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompletionsUsagePromptTokensDetails : Details of the prompt tokens.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionsUsagePromptTokensDetails {
    /// The number of cached prompt tokens.
    #[serde(rename = "cached_tokens", skip_serializing_if = "Option::is_none")]
    pub cached_tokens: Option<i32>,
}

impl CompletionsUsagePromptTokensDetails {
    /// Details of the prompt tokens.
    pub fn new() -> CompletionsUsagePromptTokensDetails {
        CompletionsUsagePromptTokensDetails {
            cached_tokens: None,
        }
    }
}

