/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CompleteUploadRequest : The request body of an upload completion request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompleteUploadRequest {
    /// The ordered list of Part IDs.
    #[serde(rename = "part_ids")]
    pub part_ids: Vec<String>,
    /// The optional md5 checksum for the file contents to verify if the bytes uploaded matches what you expect.
    #[serde(rename = "md5", skip_serializing_if = "Option::is_none")]
    pub md5: Option<String>,
}

impl CompleteUploadRequest {
    /// The request body of an upload completion request.
    pub fn new(part_ids: Vec<String>) -> CompleteUploadRequest {
        CompleteUploadRequest {
            part_ids,
            md5: None,
        }
    }
}

