/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentFilterCompletionTextSpan : Describes a span within generated completion text. Offset 0 is the first UTF32 code point of the completion text.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentFilterCompletionTextSpan {
    /// Offset of the UTF32 code point which begins the span.
    #[serde(rename = "completion_start_offset")]
    pub completion_start_offset: i32,
    /// Offset of the first UTF32 code point which is excluded from the span.  This field is always equal to completion_start_offset for empty spans.  This field is always larger than completion_start_offset for non-empty spans.
    #[serde(rename = "completion_end_offset")]
    pub completion_end_offset: i32,
}

impl ContentFilterCompletionTextSpan {
    /// Describes a span within generated completion text. Offset 0 is the first UTF32 code point of the completion text.
    pub fn new(completion_start_offset: i32, completion_end_offset: i32) -> ContentFilterCompletionTextSpan {
        ContentFilterCompletionTextSpan {
            completion_start_offset,
            completion_end_offset,
        }
    }
}

