/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateUploadRequest : The request body of an upload creation operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUploadRequest {
    /// The name of the file to upload.
    #[serde(rename = "filename")]
    pub filename: String,
    /// The intended purpose of the uploaded file.  Use 'assistants' for Assistants and Message files, 'vision' for Assistants image file inputs, 'batch' for Batch API, and 'fine-tune' for Fine-tuning.
    #[serde(rename = "purpose")]
    pub purpose: Purpose,
    /// The number of bytes in the file you are uploading.
    #[serde(rename = "bytes")]
    pub bytes: i32,
    /// The MIME type of the file.  This must fall within the supported MIME types for your file purpose. See the supported MIME types for assistants and vision.
    #[serde(rename = "mime_type")]
    pub mime_type: String,
}

impl CreateUploadRequest {
    /// The request body of an upload creation operation.
    pub fn new(filename: String, purpose: Purpose, bytes: i32, mime_type: String) -> CreateUploadRequest {
        CreateUploadRequest {
            filename,
            purpose,
            bytes,
            mime_type,
        }
    }
}
/// The intended purpose of the uploaded file.  Use 'assistants' for Assistants and Message files, 'vision' for Assistants image file inputs, 'batch' for Batch API, and 'fine-tune' for Fine-tuning.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Purpose {
    #[serde(rename = "assistants")]
    Assistants,
    #[serde(rename = "batch")]
    Batch,
    #[serde(rename = "fine-tune")]
    FineTune,
    #[serde(rename = "vision")]
    Vision,
}

impl Default for Purpose {
    fn default() -> Purpose {
        Self::Assistants
    }
}

