/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ElasticsearchQueryType : The type of Elasticsearch® retrieval query that should be executed when using it as an Azure OpenAI chat extension.
/// The type of Elasticsearch® retrieval query that should be executed when using it as an Azure OpenAI chat extension.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ElasticsearchQueryType {
    #[serde(rename = "simple")]
    Simple,
    #[serde(rename = "vector")]
    Vector,

}

impl std::fmt::Display for ElasticsearchQueryType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Simple => write!(f, "simple"),
            Self::Vector => write!(f, "vector"),
        }
    }
}

impl Default for ElasticsearchQueryType {
    fn default() -> ElasticsearchQueryType {
        Self::Simple
    }
}

