/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ElasticsearchChatExtensionConfiguration : A specific representation of configurable options for Elasticsearch when using it as an Azure OpenAI chat extension.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ElasticsearchChatExtensionConfiguration {
    #[serde(rename = "parameters")]
    pub parameters: Box<models::ElasticsearchChatExtensionParameters>,
    #[serde(rename = "type")]
    pub r#type: models::AzureChatExtensionType,
}

impl ElasticsearchChatExtensionConfiguration {
    /// A specific representation of configurable options for Elasticsearch when using it as an Azure OpenAI chat extension.
    pub fn new(parameters: models::ElasticsearchChatExtensionParameters, r#type: models::AzureChatExtensionType) -> ElasticsearchChatExtensionConfiguration {
        ElasticsearchChatExtensionConfiguration {
            parameters: Box::new(parameters),
            r#type,
        }
    }
}

