/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Embeddings : Representation of the response data from an embeddings request. Embeddings measure the relatedness of text strings and are commonly used for search, clustering, recommendations, and other similar scenarios.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Embeddings {
    /// Embedding values for the prompts submitted in the request.
    #[serde(rename = "data")]
    pub data: Vec<models::EmbeddingItem>,
    #[serde(rename = "usage")]
    pub usage: Box<models::EmbeddingsUsage>,
}

impl Embeddings {
    /// Representation of the response data from an embeddings request. Embeddings measure the relatedness of text strings and are commonly used for search, clustering, recommendations, and other similar scenarios.
    pub fn new(data: Vec<models::EmbeddingItem>, usage: models::EmbeddingsUsage) -> Embeddings {
        Embeddings {
            data,
            usage: Box::new(usage),
        }
    }
}

