/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EmbeddingItem : Representation of a single embeddings relatedness comparison.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbeddingItem {
    /// List of embeddings value for the input prompt. These represent a measurement of the vector-based relatedness of the provided input.
    #[serde(rename = "embedding")]
    pub embedding: Vec<f32>,
    /// Index of the prompt to which the EmbeddingItem corresponds.
    #[serde(rename = "index")]
    pub index: i32,
}

impl EmbeddingItem {
    /// Representation of a single embeddings relatedness comparison.
    pub fn new(embedding: Vec<f32>, index: i32) -> EmbeddingItem {
        EmbeddingItem {
            embedding,
            index,
        }
    }
}

