/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// EmbeddingsUsage : Measurement of the amount of tokens used in this request and response.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbeddingsUsage {
    /// Number of tokens sent in the original request.
    #[serde(rename = "prompt_tokens")]
    pub prompt_tokens: i32,
    /// Total number of tokens transacted in this request/response.
    #[serde(rename = "total_tokens")]
    pub total_tokens: i32,
}

impl EmbeddingsUsage {
    /// Measurement of the amount of tokens used in this request and response.
    pub fn new(prompt_tokens: i32, total_tokens: i32) -> EmbeddingsUsage {
        EmbeddingsUsage {
            prompt_tokens,
            total_tokens,
        }
    }
}

