/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FileListResponse : The response data from a file list operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileListResponse {
    /// The object type, which is always 'list'.
    #[serde(rename = "object")]
    pub object: Object,
    /// The files returned for the request.
    #[serde(rename = "data")]
    pub data: Vec<models::OpenAiFile>,
}

impl FileListResponse {
    /// The response data from a file list operation.
    pub fn new(object: Object, data: Vec<models::OpenAiFile>) -> FileListResponse {
        FileListResponse {
            object,
            data,
        }
    }
}
/// The object type, which is always 'list'.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Object {
    #[serde(rename = "list")]
    List,
}

impl Default for Object {
    fn default() -> Object {
        Self::List
    }
}

