/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// FunctionDefinition : The definition of a caller-specified function that chat completions may invoke in response to matching user input.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FunctionDefinition {
    /// The name of the function to be called.
    #[serde(rename = "name")]
    pub name: String,
    /// A description of what the function does. The model will use this description when selecting the function and interpreting its parameters.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// The parameters the function accepts, described as a JSON Schema object.
    #[serde(rename = "parameters", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<serde_json::Value>,
}

impl FunctionDefinition {
    /// The definition of a caller-specified function that chat completions may invoke in response to matching user input.
    pub fn new(name: String) -> FunctionDefinition {
        FunctionDefinition {
            name,
            description: None,
            parameters: None,
        }
    }
}

