/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageGenerationData : A representation of a single generated image, provided as either base64-encoded data or as a URL from which the image may be retrieved.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageGenerationData {
    /// The URL that provides temporary access to download the generated image.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// The complete data for an image, represented as a base64-encoded string.
    #[serde(rename = "b64_json", skip_serializing_if = "Option::is_none")]
    pub b64_json: Option<String>,
    #[serde(rename = "content_filter_results", skip_serializing_if = "Option::is_none")]
    pub content_filter_results: Option<Box<models::ImageGenerationContentFilterResults>>,
    /// The final prompt used by the model to generate the image. Only provided with dall-3-models and only when revisions were made to the prompt.
    #[serde(rename = "revised_prompt", skip_serializing_if = "Option::is_none")]
    pub revised_prompt: Option<String>,
    #[serde(rename = "prompt_filter_results", skip_serializing_if = "Option::is_none")]
    pub prompt_filter_results: Option<Box<models::ImageGenerationPromptFilterResults>>,
}

impl ImageGenerationData {
    /// A representation of a single generated image, provided as either base64-encoded data or as a URL from which the image may be retrieved.
    pub fn new() -> ImageGenerationData {
        ImageGenerationData {
            url: None,
            b64_json: None,
            content_filter_results: None,
            revised_prompt: None,
            prompt_filter_results: None,
        }
    }
}

