/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ImageGenerations : The result of a successful image generation operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageGenerations {
    /// A timestamp representing when this operation was started. Expressed in seconds since the Unix epoch of 1970-01-01T00:00:00+0000.
    #[serde(rename = "created")]
    pub created: i32,
    /// The images generated by the operation.
    #[serde(rename = "data")]
    pub data: Vec<models::ImageGenerationData>,
}

impl ImageGenerations {
    /// The result of a successful image generation operation.
    pub fn new(created: i32, data: Vec<models::ImageGenerationData>) -> ImageGenerations {
        ImageGenerations {
            created,
            data,
        }
    }
}

