/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MaxTokensFinishDetails : A structured representation of a stop reason that signifies a token limit was reached before the model could naturally complete.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MaxTokensFinishDetails {
    /// The object type.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl MaxTokensFinishDetails {
    /// A structured representation of a stop reason that signifies a token limit was reached before the model could naturally complete.
    pub fn new(r#type: String) -> MaxTokensFinishDetails {
        MaxTokensFinishDetails {
            r#type,
        }
    }
}

