/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MongoDbChatExtensionConfiguration : A specific representation of configurable options for a MongoDB chat extension configuration.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MongoDbChatExtensionConfiguration {
    #[serde(rename = "parameters")]
    pub parameters: Box<models::MongoDbChatExtensionParameters>,
    #[serde(rename = "type")]
    pub r#type: models::AzureChatExtensionType,
}

impl MongoDbChatExtensionConfiguration {
    /// A specific representation of configurable options for a MongoDB chat extension configuration.
    pub fn new(parameters: models::MongoDbChatExtensionParameters, r#type: models::AzureChatExtensionType) -> MongoDbChatExtensionConfiguration {
        MongoDbChatExtensionConfiguration {
            parameters: Box::new(parameters),
            r#type,
        }
    }
}

