/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataModelIdVectorizationSource : The details of a a vectorization source, used by Azure OpenAI On Your Data when applying vector search, that is based on a search service model ID. Currently only supported by Elasticsearch®.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnYourDataModelIdVectorizationSource {
    /// The embedding model ID build inside the search service. Currently only supported by Elasticsearch®.
    #[serde(rename = "model_id")]
    pub model_id: String,
    #[serde(rename = "type")]
    pub r#type: models::OnYourDataVectorizationSourceType,
}

impl OnYourDataModelIdVectorizationSource {
    /// The details of a a vectorization source, used by Azure OpenAI On Your Data when applying vector search, that is based on a search service model ID. Currently only supported by Elasticsearch®.
    pub fn new(model_id: String, r#type: models::OnYourDataVectorizationSourceType) -> OnYourDataModelIdVectorizationSource {
        OnYourDataModelIdVectorizationSource {
            model_id,
            r#type,
        }
    }
}

