/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataApiKeyAuthenticationOptions : The authentication options for Azure OpenAI On Your Data when using an API key.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnYourDataApiKeyAuthenticationOptions {
    /// The API key to use for authentication.
    #[serde(rename = "key")]
    pub key: String,
    #[serde(rename = "type")]
    pub r#type: models::OnYourDataAuthenticationType,
}

impl OnYourDataApiKeyAuthenticationOptions {
    /// The authentication options for Azure OpenAI On Your Data when using an API key.
    pub fn new(key: String, r#type: models::OnYourDataAuthenticationType) -> OnYourDataApiKeyAuthenticationOptions {
        OnYourDataApiKeyAuthenticationOptions {
            key,
            r#type,
        }
    }
}

