/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataVectorSearchAuthenticationOptions : The authentication options for Azure OpenAI On Your Data vector search.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum OnYourDataVectorSearchAuthenticationOptions {
    #[serde(rename="OnYourDataVectorSearchAccessTokenAuthenticationOptions")]
    OnYourDataVectorSearchAccessTokenAuthenticationOptions {
    },
    #[serde(rename="OnYourDataVectorSearchApiKeyAuthenticationOptions")]
    OnYourDataVectorSearchApiKeyAuthenticationOptions {
    },
}

impl Default for OnYourDataVectorSearchAuthenticationOptions {
    fn default() -> Self {
        Self::OnYourDataVectorSearchAccessTokenAuthenticationOptions {
        }
        
    }
}


