/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataVectorizationSourceType : Represents the available sources Azure OpenAI On Your Data can use to configure vectorization of data for use with vector search.
/// Represents the available sources Azure OpenAI On Your Data can use to configure vectorization of data for use with vector search.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OnYourDataVectorizationSourceType {
    #[serde(rename = "endpoint")]
    Endpoint,
    #[serde(rename = "deployment_name")]
    DeploymentName,
    #[serde(rename = "model_id")]
    ModelId,

}

impl std::fmt::Display for OnYourDataVectorizationSourceType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Endpoint => write!(f, "endpoint"),
            Self::DeploymentName => write!(f, "deployment_name"),
            Self::ModelId => write!(f, "model_id"),
        }
    }
}

impl Default for OnYourDataVectorizationSourceType {
    fn default() -> OnYourDataVectorizationSourceType {
        Self::Endpoint
    }
}

