/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataKeyAndKeyIdAuthenticationOptions : The authentication options for Azure OpenAI On Your Data when using an Elasticsearch key and key ID pair.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnYourDataKeyAndKeyIdAuthenticationOptions {
    /// The key to use for authentication.
    #[serde(rename = "key")]
    pub key: String,
    /// The key ID to use for authentication.
    #[serde(rename = "key_id")]
    pub key_id: String,
    #[serde(rename = "type")]
    pub r#type: models::OnYourDataAuthenticationType,
}

impl OnYourDataKeyAndKeyIdAuthenticationOptions {
    /// The authentication options for Azure OpenAI On Your Data when using an Elasticsearch key and key ID pair.
    pub fn new(key: String, key_id: String, r#type: models::OnYourDataAuthenticationType) -> OnYourDataKeyAndKeyIdAuthenticationOptions {
        OnYourDataKeyAndKeyIdAuthenticationOptions {
            key,
            key_id,
            r#type,
        }
    }
}

