/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataAuthenticationOptions : The authentication options for Azure OpenAI On Your Data.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum OnYourDataAuthenticationOptions {
    #[serde(rename="OnYourDataAccessTokenAuthenticationOptions")]
    OnYourDataAccessTokenAuthenticationOptions {
    },
    #[serde(rename="OnYourDataApiKeyAuthenticationOptions")]
    OnYourDataApiKeyAuthenticationOptions {
    },
    #[serde(rename="OnYourDataConnectionStringAuthenticationOptions")]
    OnYourDataConnectionStringAuthenticationOptions {
    },
    #[serde(rename="OnYourDataEncodedApiKeyAuthenticationOptions")]
    OnYourDataEncodedApiKeyAuthenticationOptions {
    },
    #[serde(rename="OnYourDataKeyAndKeyIdAuthenticationOptions")]
    OnYourDataKeyAndKeyIdAuthenticationOptions {
    },
    #[serde(rename="OnYourDataSystemAssignedManagedIdentityAuthenticationOptions")]
    OnYourDataSystemAssignedManagedIdentityAuthenticationOptions {
    },
    #[serde(rename="OnYourDataUserAssignedManagedIdentityAuthenticationOptions")]
    OnYourDataUserAssignedManagedIdentityAuthenticationOptions {
    },
}

impl Default for OnYourDataAuthenticationOptions {
    fn default() -> Self {
        Self::OnYourDataAccessTokenAuthenticationOptions {
        }
        
    }
}


