/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataVectorSearchAuthenticationType : The authentication types supported with Azure OpenAI On Your Data vector search.
/// The authentication types supported with Azure OpenAI On Your Data vector search.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OnYourDataVectorSearchAuthenticationType {
    #[serde(rename = "api_key")]
    ApiKey,
    #[serde(rename = "access_token")]
    AccessToken,

}

impl std::fmt::Display for OnYourDataVectorSearchAuthenticationType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::ApiKey => write!(f, "api_key"),
            Self::AccessToken => write!(f, "access_token"),
        }
    }
}

impl Default for OnYourDataVectorSearchAuthenticationType {
    fn default() -> OnYourDataVectorSearchAuthenticationType {
        Self::ApiKey
    }
}

