/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataConnectionStringAuthenticationOptions : The authentication options for Azure OpenAI On Your Data when using a connection string.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnYourDataConnectionStringAuthenticationOptions {
    /// The connection string to use for authentication.
    #[serde(rename = "connection_string")]
    pub connection_string: String,
    #[serde(rename = "type")]
    pub r#type: models::OnYourDataAuthenticationType,
}

impl OnYourDataConnectionStringAuthenticationOptions {
    /// The authentication options for Azure OpenAI On Your Data when using a connection string.
    pub fn new(connection_string: String, r#type: models::OnYourDataAuthenticationType) -> OnYourDataConnectionStringAuthenticationOptions {
        OnYourDataConnectionStringAuthenticationOptions {
            connection_string,
            r#type,
        }
    }
}

