/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataEncodedApiKeyAuthenticationOptions : The authentication options for Azure OpenAI On Your Data when using an Elasticsearch encoded API key.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnYourDataEncodedApiKeyAuthenticationOptions {
    /// The encoded API key to use for authentication.
    #[serde(rename = "encoded_api_key")]
    pub encoded_api_key: String,
    #[serde(rename = "type")]
    pub r#type: models::OnYourDataAuthenticationType,
}

impl OnYourDataEncodedApiKeyAuthenticationOptions {
    /// The authentication options for Azure OpenAI On Your Data when using an Elasticsearch encoded API key.
    pub fn new(encoded_api_key: String, r#type: models::OnYourDataAuthenticationType) -> OnYourDataEncodedApiKeyAuthenticationOptions {
        OnYourDataEncodedApiKeyAuthenticationOptions {
            encoded_api_key,
            r#type,
        }
    }
}

