/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataDeploymentNameVectorizationSource : The details of a a vectorization source, used by Azure OpenAI On Your Data when applying vector search, that is based on an internal embeddings model deployment name in the same Azure OpenAI resource.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnYourDataDeploymentNameVectorizationSource {
    /// The embedding model deployment name within the same Azure OpenAI resource. This enables you to use vector search without Azure OpenAI api-key and without Azure OpenAI public network access.
    #[serde(rename = "deployment_name")]
    pub deployment_name: String,
    /// The number of dimensions the embeddings should have. Only supported in `text-embedding-3` and later models.
    #[serde(rename = "dimensions", skip_serializing_if = "Option::is_none")]
    pub dimensions: Option<i32>,
    #[serde(rename = "type")]
    pub r#type: models::OnYourDataVectorizationSourceType,
}

impl OnYourDataDeploymentNameVectorizationSource {
    /// The details of a a vectorization source, used by Azure OpenAI On Your Data when applying vector search, that is based on an internal embeddings model deployment name in the same Azure OpenAI resource.
    pub fn new(deployment_name: String, r#type: models::OnYourDataVectorizationSourceType) -> OnYourDataDeploymentNameVectorizationSource {
        OnYourDataDeploymentNameVectorizationSource {
            deployment_name,
            dimensions: None,
            r#type,
        }
    }
}

