/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataVectorizationSource : An abstract representation of a vectorization source for Azure OpenAI On Your Data with vector search.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum OnYourDataVectorizationSource {
    #[serde(rename="OnYourDataDeploymentNameVectorizationSource")]
    OnYourDataDeploymentNameVectorizationSource {
    },
    #[serde(rename="OnYourDataEndpointVectorizationSource")]
    OnYourDataEndpointVectorizationSource {
    },
    #[serde(rename="OnYourDataIntegratedVectorizationSource")]
    OnYourDataIntegratedVectorizationSource {
    },
    #[serde(rename="OnYourDataModelIdVectorizationSource")]
    OnYourDataModelIdVectorizationSource {
    },
}

impl Default for OnYourDataVectorizationSource {
    fn default() -> Self {
        Self::OnYourDataDeploymentNameVectorizationSource {
        }
        
    }
}


