/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataContextProperty : The context property.
/// The context property.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OnYourDataContextProperty {
    #[serde(rename = "citations")]
    Citations,
    #[serde(rename = "intent")]
    Intent,
    #[serde(rename = "all_retrieved_documents")]
    AllRetrievedDocuments,

}

impl std::fmt::Display for OnYourDataContextProperty {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Citations => write!(f, "citations"),
            Self::Intent => write!(f, "intent"),
            Self::AllRetrievedDocuments => write!(f, "all_retrieved_documents"),
        }
    }
}

impl Default for OnYourDataContextProperty {
    fn default() -> OnYourDataContextProperty {
        Self::Citations
    }
}

