/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataEndpointVectorizationSource : The details of a a vectorization source, used by Azure OpenAI On Your Data when applying vector search, that is based on a public Azure OpenAI endpoint call for embeddings.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnYourDataEndpointVectorizationSource {
    /// Specifies the resource endpoint URL from which embeddings should be retrieved. It should be in the format of https://YOUR_RESOURCE_NAME.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/embeddings. The api-version query parameter is not allowed.
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    #[serde(rename = "authentication")]
    pub authentication: Box<models::OnYourDataVectorSearchAuthenticationOptions>,
    #[serde(rename = "type")]
    pub r#type: models::OnYourDataVectorizationSourceType,
}

impl OnYourDataEndpointVectorizationSource {
    /// The details of a a vectorization source, used by Azure OpenAI On Your Data when applying vector search, that is based on a public Azure OpenAI endpoint call for embeddings.
    pub fn new(endpoint: String, authentication: models::OnYourDataVectorSearchAuthenticationOptions, r#type: models::OnYourDataVectorizationSourceType) -> OnYourDataEndpointVectorizationSource {
        OnYourDataEndpointVectorizationSource {
            endpoint,
            authentication: Box::new(authentication),
            r#type,
        }
    }
}

