/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataUsernameAndPasswordAuthenticationOptions : The authentication options for Azure OpenAI On Your Data when using a username and password.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnYourDataUsernameAndPasswordAuthenticationOptions {
    /// The username.
    #[serde(rename = "username")]
    pub username: String,
    /// The password.
    #[serde(rename = "password")]
    pub password: String,
    #[serde(rename = "type")]
    pub r#type: models::OnYourDataAuthenticationType,
}

impl OnYourDataUsernameAndPasswordAuthenticationOptions {
    /// The authentication options for Azure OpenAI On Your Data when using a username and password.
    pub fn new(username: String, password: String, r#type: models::OnYourDataAuthenticationType) -> OnYourDataUsernameAndPasswordAuthenticationOptions {
        OnYourDataUsernameAndPasswordAuthenticationOptions {
            username,
            password,
            r#type,
        }
    }
}

