/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataUserAssignedManagedIdentityAuthenticationOptions : The authentication options for Azure OpenAI On Your Data when using a user-assigned managed identity.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnYourDataUserAssignedManagedIdentityAuthenticationOptions {
    /// The resource ID of the user-assigned managed identity to use for authentication.
    #[serde(rename = "managed_identity_resource_id")]
    pub managed_identity_resource_id: String,
    #[serde(rename = "type")]
    pub r#type: models::OnYourDataAuthenticationType,
}

impl OnYourDataUserAssignedManagedIdentityAuthenticationOptions {
    /// The authentication options for Azure OpenAI On Your Data when using a user-assigned managed identity.
    pub fn new(managed_identity_resource_id: String, r#type: models::OnYourDataAuthenticationType) -> OnYourDataUserAssignedManagedIdentityAuthenticationOptions {
        OnYourDataUserAssignedManagedIdentityAuthenticationOptions {
            managed_identity_resource_id,
            r#type,
        }
    }
}

