/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataIntegratedVectorizationSource : Represents the integrated vectorizer defined within the search resource.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnYourDataIntegratedVectorizationSource {
    #[serde(rename = "type")]
    pub r#type: models::OnYourDataVectorizationSourceType,
}

impl OnYourDataIntegratedVectorizationSource {
    /// Represents the integrated vectorizer defined within the search resource.
    pub fn new(r#type: models::OnYourDataVectorizationSourceType) -> OnYourDataIntegratedVectorizationSource {
        OnYourDataIntegratedVectorizationSource {
            r#type,
        }
    }
}

