/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataSystemAssignedManagedIdentityAuthenticationOptions : The authentication options for Azure OpenAI On Your Data when using a system-assigned managed identity.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnYourDataSystemAssignedManagedIdentityAuthenticationOptions {
    #[serde(rename = "type")]
    pub r#type: models::OnYourDataAuthenticationType,
}

impl OnYourDataSystemAssignedManagedIdentityAuthenticationOptions {
    /// The authentication options for Azure OpenAI On Your Data when using a system-assigned managed identity.
    pub fn new(r#type: models::OnYourDataAuthenticationType) -> OnYourDataSystemAssignedManagedIdentityAuthenticationOptions {
        OnYourDataSystemAssignedManagedIdentityAuthenticationOptions {
            r#type,
        }
    }
}

