/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataAccessTokenAuthenticationOptions : The authentication options for Azure OpenAI On Your Data when using access token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnYourDataAccessTokenAuthenticationOptions {
    /// The access token to use for authentication.
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde(rename = "type")]
    pub r#type: models::OnYourDataAuthenticationType,
}

impl OnYourDataAccessTokenAuthenticationOptions {
    /// The authentication options for Azure OpenAI On Your Data when using access token.
    pub fn new(access_token: String, r#type: models::OnYourDataAuthenticationType) -> OnYourDataAccessTokenAuthenticationOptions {
        OnYourDataAccessTokenAuthenticationOptions {
            access_token,
            r#type,
        }
    }
}

