/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-10-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OnYourDataVectorSearchAccessTokenAuthenticationOptions : The authentication options for Azure OpenAI On Your Data vector search when using access token.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnYourDataVectorSearchAccessTokenAuthenticationOptions {
    /// The access token to use for authentication.
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde(rename = "type")]
    pub r#type: models::OnYourDataVectorSearchAuthenticationType,
}

impl OnYourDataVectorSearchAccessTokenAuthenticationOptions {
    /// The authentication options for Azure OpenAI On Your Data vector search when using access token.
    pub fn new(access_token: String, r#type: models::OnYourDataVectorSearchAuthenticationType) -> OnYourDataVectorSearchAccessTokenAuthenticationOptions {
        OnYourDataVectorSearchAccessTokenAuthenticationOptions {
            access_token,
            r#type,
        }
    }
}

