/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PineconeChatExtensionConfiguration : A specific representation of configurable options for Pinecone when using it as an Azure OpenAI chat extension.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PineconeChatExtensionConfiguration {
    #[serde(rename = "parameters")]
    pub parameters: Box<models::PineconeChatExtensionParameters>,
    #[serde(rename = "type")]
    pub r#type: models::AzureChatExtensionType,
}

impl PineconeChatExtensionConfiguration {
    /// A specific representation of configurable options for Pinecone when using it as an Azure OpenAI chat extension.
    pub fn new(parameters: models::PineconeChatExtensionParameters, r#type: models::AzureChatExtensionType) -> PineconeChatExtensionConfiguration {
        PineconeChatExtensionConfiguration {
            parameters: Box::new(parameters),
            r#type,
        }
    }
}

