/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SpeechVoice : The available voices for text-to-speech.
/// The available voices for text-to-speech.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SpeechVoice {
    #[serde(rename = "alloy")]
    Alloy,
    #[serde(rename = "echo")]
    Echo,
    #[serde(rename = "fable")]
    Fable,
    #[serde(rename = "onyx")]
    Onyx,
    #[serde(rename = "nova")]
    Nova,
    #[serde(rename = "shimmer")]
    Shimmer,

}

impl std::fmt::Display for SpeechVoice {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Alloy => write!(f, "alloy"),
            Self::Echo => write!(f, "echo"),
            Self::Fable => write!(f, "fable"),
            Self::Onyx => write!(f, "onyx"),
            Self::Nova => write!(f, "nova"),
            Self::Shimmer => write!(f, "shimmer"),
        }
    }
}

impl Default for SpeechVoice {
    fn default() -> SpeechVoice {
        Self::Alloy
    }
}

