/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SpeechGenerationOptions : A representation of the request options that control the behavior of a text-to-speech operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SpeechGenerationOptions {
    /// The text to generate audio for. The maximum length is 4096 characters.
    #[serde(rename = "input")]
    pub input: String,
    #[serde(rename = "voice")]
    pub voice: models::SpeechVoice,
    /// The audio output format for the spoken text. By default, the MP3 format will be used.
    #[serde(rename = "response_format", skip_serializing_if = "Option::is_none")]
    pub response_format: Option<ResponseFormat>,
    /// The speed of speech for generated audio. Values are valid in the range from 0.25 to 4.0, with 1.0 the default and higher values corresponding to faster speech.
    #[serde(rename = "speed", skip_serializing_if = "Option::is_none")]
    pub speed: Option<f32>,
    /// The model to use for this text-to-speech request.
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
}

impl SpeechGenerationOptions {
    /// A representation of the request options that control the behavior of a text-to-speech operation.
    pub fn new(input: String, voice: models::SpeechVoice) -> SpeechGenerationOptions {
        SpeechGenerationOptions {
            input,
            voice,
            response_format: None,
            speed: None,
            model: None,
        }
    }
}
/// The audio output format for the spoken text. By default, the MP3 format will be used.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ResponseFormat {
    #[serde(rename = "mp3")]
    Mp3,
    #[serde(rename = "opus")]
    Opus,
    #[serde(rename = "aac")]
    Aac,
    #[serde(rename = "flac")]
    Flac,
    #[serde(rename = "wav")]
    Wav,
    #[serde(rename = "pcm")]
    Pcm,
}

impl Default for ResponseFormat {
    fn default() -> ResponseFormat {
        Self::Mp3
    }
}

