/*
 * Azure OpenAI API
 *
 * Azure OpenAI APIs for completions and search
 *
 * The version of the OpenAPI document: 2024-05-01-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StopFinishDetails : A structured representation of a stop reason that signifies natural termination by the model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StopFinishDetails {
    /// The token sequence that the model terminated with.
    #[serde(rename = "stop")]
    pub stop: String,
    /// The object type.
    #[serde(rename = "type")]
    pub r#type: String,
}

impl StopFinishDetails {
    /// A structured representation of a stop reason that signifies natural termination by the model.
    pub fn new(stop: String, r#type: String) -> StopFinishDetails {
        StopFinishDetails {
            stop,
            r#type,
        }
    }
}

